In [9]:
import pandas as pd

# Cargar la tabla original
timesheet = pd.read_csv('../data/timesheet.csv')

# Calcular el promedio de horas por conductor y conservar todos los registros
timesheet_with_means = timesheet.copy()
timesheet_with_means['mean_hours-logged'] = timesheet_with_means.groupby('driverId')['hours-logged'].transform('mean')

timesheet_with_means

      driverId  week  hours-logged  miles-logged  mean_hours-logged
0           10     1            70          3300          62.153846
1           10     2            70          3300          62.153846
2           10     3            60          2800          62.153846
3           10     4            70          3100          62.153846
4           10     5            70          3200          62.153846
...        ...   ...           ...           ...                ...
1763        43    48            52          2517          52.884615
1764        43    49            56          2743          52.884615
1765        43    50            59          2665          52.884615
1766        43    51            58          2593          52.884615
1767        43    52            48          2764          52.884615

[1768 rows x 5 columns]

In [10]:
# Crear la tabla con el promedio de horas de cada conductor
timesheet_with_means = timesheet.copy()
timesheet_with_means['mean_hours-logged'] = timesheet_with_means.groupby('driverId')['hours-logged'].transform('mean')

timesheet_with_means

      driverId  week  hours-logged  miles-logged  mean_hours-logged
0           10     1            70          3300          62.153846
1           10     2            70          3300          62.153846
2           10     3            60          2800          62.153846
3           10     4            70          3100          62.153846
4           10     5            70          3200          62.153846
...        ...   ...           ...           ...                ...
1763        43    48            52          2517          52.884615
1764        43    49            56          2743          52.884615
1765        43    50            59          2665          52.884615
1766        43    51            58          2593          52.884615
1767        43    52            48          2764          52.884615

[1768 rows x 5 columns]

In [11]:
# Sumar horas y millas por conductor
sum_timesheet = timesheet.groupby('driverId', as_index=False)[['hours-logged', 'miles-logged']].sum()
sum_timesheet

    driverId  hours-logged  miles-logged
0         10          3232        147150
1         11          3642        179300
2         12          2639        135962
3         13          2727        134126
4         14          2781        136624
5         15          2734        138750
6         16          2746        137205
7         17          2701        135992
8         18          2654        137834
9         19          2738        137968
10        20          2644        134564
11        21          2751        138719
12        22          2733        137550
13        23          2750        137980
14        24          2647        134461
15        25          2723        139180
16        26          2730        137530
17        27          2771        137922
18        28          2723        137469
19        29          2760        138255
20        30          2773        137473
21        31          2704        137057
22        32          2736        137422
23        33          2759        139285
24        34          2811        137728
25        35          2728        138727
26        36          2795        138025
27        37          2694        137223
28        38          2760        137464
29        39          2745        138788
30        40          2700        136931
31        41          2723        138407
32        42          2697        136673
33        43          2750        136993

In [12]:
# Calcular mínimo y máximo de horas registradas por conductor
min_max_timesheet = timesheet.groupby('driverId', as_index=False).agg(min_hours_logged=('hours-logged', 'min'), max_hours_logged=('hours-logged', 'max'))
min_max_timesheet

    driverId  min_hours_logged  max_hours_logged
0         10                 0                76
1         11                 0                92
2         12                 0                60
3         13                10                60
4         14                45                60
5         15                45                60
6         16                45                60
7         17                20                60
8         18                45                60
9         19                45                60
10        20                 0                60
11        21                45                60
12        22                45                60
13        23                45                60
14        24                 0                60
15        25                45                60
16        26                45                60
17        27                45                60
18        28                45                60
19        29                45                60
20        30                45                60
21        31                45                60
22        32                45                60
23        33                46                60
24        34                45                60
25        35                45                60
26        36                45                60
27        37                45                59
28        38                45                60
29        39                45                60
30        40                45                60
31        41                45                60
32        42                45                60
33        43                46                60

In [13]:
# Combinar los totales por conductor con su nombre
drivers = pd.read_csv('../data/drivers.csv')
summary = sum_timesheet.merge(drivers[['driverId', 'name']], on='driverId', how='left')
summary = summary[['driverId', 'hours-logged', 'miles-logged', 'name']]
summary

    driverId  hours-logged  miles-logged                 name
0         10          3232        147150    George Vetticaden
1         11          3642        179300       Jamie Engesser
2         12          2639        135962          Paul Coddin
3         13          2727        134126          Joe Niemiec
4         14          2781        136624           Adis Cesir
5         15          2734        138750         Rohit Bakshi
6         16          2746        137205           Tom McCuch
7         17          2701        135992          Eric Mizell
8         18          2654        137834            Grant Liu
9         19          2738        137968           Ajay Singh
10        20          2644        134564         Chris Harris
11        21          2751        138719         Jeff Markham
12        22          2733        137550        Nadeem Asghar
13        23          2750        137980            Adam Diaz
14        24          2647        134461          Don Hilborn
15        25          2723        139180  Jean-Philippe Playe
16        26          2730        137530         Michael Aube
17        27          2771        137922      Mark Lochbihler
18        28          2723        137469      Olivier Renault
19        29          2760        138255           Teddy Choi
20        30          2773        137473             Dan Rice
21        31          2704        137057        Rommel Garcia
22        32          2736        137422       Ryan Templeton
23        33          2759        139285    Sridhara Sabbella
24        34          2811        137728         Frank Romano
25        35          2728        138727          Emil Siemes
26        36          2795        138025        Andrew Grande
27        37          2694        137223            Wes Floyd
28        38          2760        137464           Scott Shaw
29        39          2745        138788         David Kaiser
30        40          2700        136931     Nicolas Maillard
31        41          2723        138407        Greg Phillips
32        42          2697        136673      Randy Gelhausen
33        43          2750        136993          Dave Patton

In [14]:
# Guardar summary como CSV, sin incluir el índice
summary.to_csv('../submission/summary.csv', index=False)

In [15]:
# Seleccionar los diez conductores con mayor total de millas
top10 = summary.nlargest(10, 'miles-logged').reset_index(drop=True)
top10

   driverId  hours-logged  miles-logged                 name
0        11          3642        179300       Jamie Engesser
1        10          3232        147150    George Vetticaden
2        33          2759        139285    Sridhara Sabbella
3        25          2723        139180  Jean-Philippe Playe
4        39          2745        138788         David Kaiser
5        15          2734        138750         Rohit Bakshi
6        35          2728        138727          Emil Siemes
7        21          2751        138719         Jeff Markham
8        41          2723        138407        Greg Phillips
9        29          2760        138255           Teddy Choi

In [16]:
import matplotlib.pyplot as plt

# Graficar los diez conductores con más millas
top10_plot = top10.sort_values('miles-logged', ascending=True)
fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(top10_plot['name'], top10_plot['miles-logged'])
ax.set_xlabel('Millas registradas')
ax.set_ylabel('Conductor')
ax.set_title('Top 10 conductores por millas registradas')
fig.tight_layout()
fig.savefig('../submission/top10_drivers.png', dpi=150, bbox_inches='tight')
plt.show()